// <auto-generated />
using System;
using HotelBookingProject0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBookingProject0.Migrations
{
    [DbContext(typeof(HotelBookingContext))]
    [Migration("20260320201544_RealisticSeedData")]
    partial class RealisticSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmenityRoom", b =>
                {
                    b.Property<int>("AmenitiesAmenityID")
                        .HasColumnType("int");

                    b.Property<int>("RoomsRoomID")
                        .HasColumnType("int");

                    b.HasKey("AmenitiesAmenityID", "RoomsRoomID");

                    b.HasIndex("RoomsRoomID");

                    b.ToTable("AmenityRoom");

                    b.HasData(
                        new
                        {
                            AmenitiesAmenityID = 1,
                            RoomsRoomID = 1
                        },
                        new
                        {
                            AmenitiesAmenityID = 2,
                            RoomsRoomID = 1
                        },
                        new
                        {
                            AmenitiesAmenityID = 2,
                            RoomsRoomID = 2
                        },
                        new
                        {
                            AmenitiesAmenityID = 3,
                            RoomsRoomID = 2
                        },
                        new
                        {
                            AmenitiesAmenityID = 3,
                            RoomsRoomID = 3
                        },
                        new
                        {
                            AmenitiesAmenityID = 4,
                            RoomsRoomID = 3
                        },
                        new
                        {
                            AmenitiesAmenityID = 4,
                            RoomsRoomID = 4
                        },
                        new
                        {
                            AmenitiesAmenityID = 5,
                            RoomsRoomID = 4
                        },
                        new
                        {
                            AmenitiesAmenityID = 5,
                            RoomsRoomID = 5
                        },
                        new
                        {
                            AmenitiesAmenityID = 6,
                            RoomsRoomID = 5
                        },
                        new
                        {
                            AmenitiesAmenityID = 6,
                            RoomsRoomID = 6
                        },
                        new
                        {
                            AmenitiesAmenityID = 7,
                            RoomsRoomID = 6
                        },
                        new
                        {
                            AmenitiesAmenityID = 7,
                            RoomsRoomID = 7
                        },
                        new
                        {
                            AmenitiesAmenityID = 8,
                            RoomsRoomID = 7
                        },
                        new
                        {
                            AmenitiesAmenityID = 8,
                            RoomsRoomID = 8
                        },
                        new
                        {
                            AmenitiesAmenityID = 9,
                            RoomsRoomID = 8
                        },
                        new
                        {
                            AmenitiesAmenityID = 9,
                            RoomsRoomID = 9
                        },
                        new
                        {
                            AmenitiesAmenityID = 10,
                            RoomsRoomID = 9
                        },
                        new
                        {
                            AmenitiesAmenityID = 10,
                            RoomsRoomID = 10
                        },
                        new
                        {
                            AmenitiesAmenityID = 11,
                            RoomsRoomID = 10
                        },
                        new
                        {
                            AmenitiesAmenityID = 11,
                            RoomsRoomID = 11
                        },
                        new
                        {
                            AmenitiesAmenityID = 12,
                            RoomsRoomID = 11
                        },
                        new
                        {
                            AmenitiesAmenityID = 12,
                            RoomsRoomID = 12
                        },
                        new
                        {
                            AmenitiesAmenityID = 13,
                            RoomsRoomID = 12
                        },
                        new
                        {
                            AmenitiesAmenityID = 13,
                            RoomsRoomID = 13
                        },
                        new
                        {
                            AmenitiesAmenityID = 14,
                            RoomsRoomID = 13
                        },
                        new
                        {
                            AmenitiesAmenityID = 14,
                            RoomsRoomID = 14
                        },
                        new
                        {
                            AmenitiesAmenityID = 15,
                            RoomsRoomID = 14
                        },
                        new
                        {
                            AmenitiesAmenityID = 15,
                            RoomsRoomID = 15
                        },
                        new
                        {
                            AmenitiesAmenityID = 16,
                            RoomsRoomID = 15
                        },
                        new
                        {
                            AmenitiesAmenityID = 16,
                            RoomsRoomID = 16
                        },
                        new
                        {
                            AmenitiesAmenityID = 17,
                            RoomsRoomID = 16
                        },
                        new
                        {
                            AmenitiesAmenityID = 17,
                            RoomsRoomID = 17
                        },
                        new
                        {
                            AmenitiesAmenityID = 18,
                            RoomsRoomID = 17
                        },
                        new
                        {
                            AmenitiesAmenityID = 18,
                            RoomsRoomID = 18
                        },
                        new
                        {
                            AmenitiesAmenityID = 19,
                            RoomsRoomID = 18
                        },
                        new
                        {
                            AmenitiesAmenityID = 19,
                            RoomsRoomID = 19
                        },
                        new
                        {
                            AmenitiesAmenityID = 20,
                            RoomsRoomID = 19
                        },
                        new
                        {
                            AmenitiesAmenityID = 20,
                            RoomsRoomID = 20
                        },
                        new
                        {
                            AmenitiesAmenityID = 1,
                            RoomsRoomID = 20
                        });
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.Amenity", b =>
                {
                    b.Property<int>("AmenityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityID"));

                    b.Property<int?>("HotelID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AmenityID");

                    b.HasIndex("HotelID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            AmenityID = 1,
                            Name = "Free Wi-Fi"
                        },
                        new
                        {
                            AmenityID = 2,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            AmenityID = 3,
                            Name = "Breakfast Included"
                        },
                        new
                        {
                            AmenityID = 4,
                            Name = "Free Parking"
                        },
                        new
                        {
                            AmenityID = 5,
                            Name = "Swimming Pool"
                        },
                        new
                        {
                            AmenityID = 6,
                            Name = "Spa"
                        },
                        new
                        {
                            AmenityID = 7,
                            Name = "Fitness Center"
                        },
                        new
                        {
                            AmenityID = 8,
                            Name = "On-site Restaurant"
                        },
                        new
                        {
                            AmenityID = 9,
                            Name = "Bar / Lounge"
                        },
                        new
                        {
                            AmenityID = 10,
                            Name = "24-hour Room Service"
                        },
                        new
                        {
                            AmenityID = 11,
                            Name = "Pet Friendly"
                        },
                        new
                        {
                            AmenityID = 12,
                            Name = "Non-smoking Rooms"
                        },
                        new
                        {
                            AmenityID = 13,
                            Name = "Airport Shuttle"
                        },
                        new
                        {
                            AmenityID = 14,
                            Name = "Laundry Service"
                        },
                        new
                        {
                            AmenityID = 15,
                            Name = "24-hour Front Desk"
                        },
                        new
                        {
                            AmenityID = 16,
                            Name = "Business Center"
                        },
                        new
                        {
                            AmenityID = 17,
                            Name = "Concierge"
                        },
                        new
                        {
                            AmenityID = 18,
                            Name = "Children's Activities"
                        },
                        new
                        {
                            AmenityID = 19,
                            Name = "Sauna"
                        },
                        new
                        {
                            AmenityID = 20,
                            Name = "Beach Access"
                        });
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookingID");

                    b.HasIndex("RoomID");

                    b.HasIndex("UserID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.Hotel", b =>
                {
                    b.Property<int>("HotelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("StarRating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("HotelID");

                    b.ToTable("hotels");

                    b.HasData(
                        new
                        {
                            HotelID = 1,
                            Address = "123 Madison Ave, New York, NY",
                            City = "New York",
                            Description = "Classic luxury hotel with skyline views, close to central attractions.",
                            Name = "Grandview Hotel",
                            StarRating = 5,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 2,
                            Address = "200 Ocean Drive, Santa Monica, CA",
                            City = "Los Angeles",
                            Description = "Beachfront resort with pools and spa, perfect for seaside getaways.",
                            Name = "Pacific Bay Resort",
                            StarRating = 4,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 3,
                            Address = "45 River St, Chicago, IL",
                            City = "Chicago",
                            Description = "Comfortable riverside hotel near downtown and cultural sites.",
                            Name = "Riverside Inn",
                            StarRating = 3,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 4,
                            Address = "77 Ocean Blvd, Miami, FL",
                            City = "Miami",
                            Description = "Modern rooms with sea views, rooftop bar and pool.",
                            Name = "Sunset Bay Hotel",
                            StarRating = 4,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 5,
                            Address = "10 Market St, San Francisco, CA",
                            City = "San Francisco",
                            Description = "Upscale suites in the heart of the city, near shops and dining.",
                            Name = "Market Street Suites",
                            StarRating = 4,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 6,
                            Address = "300 Pine St, Seattle, WA",
                            City = "Seattle",
                            Description = "Cozy lodge-style hotel near parks and waterfront.",
                            Name = "Evergreen Lodge",
                            StarRating = 3,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 7,
                            Address = "88 Beacon St, Boston, MA",
                            City = "Boston",
                            Description = "Historic hotel with classic rooms and easy access to universities and museums.",
                            Name = "Beacon Hill Hotel",
                            StarRating = 4,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 8,
                            Address = "150 Congress Ave, Austin, TX",
                            City = "Austin",
                            Description = "Boutique hotel close to live music venues and nightlife.",
                            Name = "Lone Star Inn",
                            StarRating = 3,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 9,
                            Address = "1 Mountain Road, Denver, CO",
                            City = "Denver",
                            Description = "Mountain-adjacent resort offering ski access and outdoor activities.",
                            Name = "Highland Peaks Resort",
                            StarRating = 4,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 10,
                            Address = "500 Theme Park Way, Orlando, FL",
                            City = "Orlando",
                            Description = "Family-friendly suites steps from major attractions.",
                            Name = "Orlando Family Suites",
                            StarRating = 3,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 11,
                            Address = "777 Strip Ave, Las Vegas, NV",
                            City = "Las Vegas",
                            Description = "Luxury hotel on the Strip with entertainment and dining.",
                            Name = "Desert Oasis Hotel",
                            StarRating = 5,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 12,
                            Address = "21 Riverbank Dr, Portland, OR",
                            City = "Portland",
                            Description = "Eco-friendly hotel with farm-to-table dining and river views.",
                            Name = "Willamette Riverside",
                            StarRating = 3,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 13,
                            Address = "123 Harbor Ln, San Diego, CA",
                            City = "San Diego",
                            Description = "Seaside hotel with family activities and marina access.",
                            Name = "Cabrillo Seaside",
                            StarRating = 4,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 14,
                            Address = "250 Waikiki Beach Rd, Honolulu, HI",
                            City = "Honolulu",
                            Description = "Tropical resort with beach access and cultural activities.",
                            Name = "Honolulu Beach Resort",
                            StarRating = 5,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 15,
                            Address = "75 Peachtree St, Atlanta, GA",
                            City = "Atlanta",
                            Description = "Downtown hotel with panoramic city views and conference facilities.",
                            Name = "Peachtree Plaza",
                            StarRating = 4,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 16,
                            Address = "45 Independence Mall, Philadelphia, PA",
                            City = "Philadelphia",
                            Description = "Historic-area hotel, ideal for sightseeing and business travel.",
                            Name = "Liberty House",
                            StarRating = 3,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 17,
                            Address = "12 Lakeview Dr, Dallas, TX",
                            City = "Dallas",
                            Description = "Quiet lakeside hotel with modern amenities and meeting space.",
                            Name = "Lakeside Retreat",
                            StarRating = 3,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 18,
                            Address = "900 Desert Rd, Phoenix, AZ",
                            City = "Phoenix",
                            Description = "Resort with pools, spa, and golf nearby.",
                            Name = "Desert Sun Resort",
                            StarRating = 4,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 19,
                            Address = "330 Hennepin Ave, Minneapolis, MN",
                            City = "Minneapolis",
                            Description = "Urban hotel with convenient transit access and dining.",
                            Name = "Midtown Commons",
                            StarRating = 3,
                            Status = 0
                        },
                        new
                        {
                            HotelID = 20,
                            Address = "200 Broadway, Nashville, TN",
                            City = "Nashville",
                            Description = "Boutique suites close to music venues and nightlife.",
                            Name = "Music City Suites",
                            StarRating = 4,
                            Status = 0
                        });
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.HotelImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("ImageID");

                    b.HasIndex("HotelID");

                    b.ToTable("HotelImages");

                    b.HasData(
                        new
                        {
                            ImageID = 1,
                            HotelID = 1,
                            ImageURL = "https://images.unsplash.com/photo-1501117716987-c8e6f8b7a6f8?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 2,
                            HotelID = 1,
                            ImageURL = "https://images.unsplash.com/photo-1501117619481-8dde0d6d6aef?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 3,
                            HotelID = 2,
                            ImageURL = "https://images.unsplash.com/photo-1501117619481-8dde0d6d6aef?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 4,
                            HotelID = 2,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-1?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 5,
                            HotelID = 3,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-1?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 6,
                            HotelID = 3,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-2?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 7,
                            HotelID = 4,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-2?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 8,
                            HotelID = 4,
                            ImageURL = "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 9,
                            HotelID = 5,
                            ImageURL = "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 10,
                            HotelID = 5,
                            ImageURL = "https://images.unsplash.com/photo-1501117716987-c8e6f8b7a6f8?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 11,
                            HotelID = 6,
                            ImageURL = "https://images.unsplash.com/photo-1501117716987-c8e6f8b7a6f8?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 12,
                            HotelID = 6,
                            ImageURL = "https://images.unsplash.com/photo-1501117619481-8dde0d6d6aef?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 13,
                            HotelID = 7,
                            ImageURL = "https://images.unsplash.com/photo-1501117619481-8dde0d6d6aef?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 14,
                            HotelID = 7,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-1?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 15,
                            HotelID = 8,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-1?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 16,
                            HotelID = 8,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-2?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 17,
                            HotelID = 9,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-2?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 18,
                            HotelID = 9,
                            ImageURL = "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 19,
                            HotelID = 10,
                            ImageURL = "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 20,
                            HotelID = 10,
                            ImageURL = "https://images.unsplash.com/photo-1501117716987-c8e6f8b7a6f8?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 21,
                            HotelID = 11,
                            ImageURL = "https://images.unsplash.com/photo-1501117716987-c8e6f8b7a6f8?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 22,
                            HotelID = 11,
                            ImageURL = "https://images.unsplash.com/photo-1501117619481-8dde0d6d6aef?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 23,
                            HotelID = 12,
                            ImageURL = "https://images.unsplash.com/photo-1501117619481-8dde0d6d6aef?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 24,
                            HotelID = 12,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-1?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 25,
                            HotelID = 13,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-1?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 26,
                            HotelID = 13,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-2?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 27,
                            HotelID = 14,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-2?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 28,
                            HotelID = 14,
                            ImageURL = "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 29,
                            HotelID = 15,
                            ImageURL = "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 30,
                            HotelID = 15,
                            ImageURL = "https://images.unsplash.com/photo-1501117716987-c8e6f8b7a6f8?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 31,
                            HotelID = 16,
                            ImageURL = "https://images.unsplash.com/photo-1501117716987-c8e6f8b7a6f8?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 32,
                            HotelID = 16,
                            ImageURL = "https://images.unsplash.com/photo-1501117619481-8dde0d6d6aef?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 33,
                            HotelID = 17,
                            ImageURL = "https://images.unsplash.com/photo-1501117619481-8dde0d6d6aef?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 34,
                            HotelID = 17,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-1?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 35,
                            HotelID = 18,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-1?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 36,
                            HotelID = 18,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-2?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 37,
                            HotelID = 19,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-2?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 38,
                            HotelID = 19,
                            ImageURL = "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        },
                        new
                        {
                            ImageID = 39,
                            HotelID = 20,
                            ImageURL = "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = true
                        },
                        new
                        {
                            ImageID = 40,
                            HotelID = 20,
                            ImageURL = "https://images.unsplash.com/photo-1501117716987-c8e6f8b7a6f8?auto=format&fit=crop&w=1600&q=80",
                            IsPrimary = false
                        });
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewID");

                    b.HasIndex("HotelID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.HasKey("RoomID");

                    b.HasIndex("HotelID");

                    b.HasIndex("TypeID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomID = 1,
                            HotelID = 1,
                            IsAvailable = true,
                            RoomNumber = "101",
                            TypeID = 5
                        },
                        new
                        {
                            RoomID = 2,
                            HotelID = 2,
                            IsAvailable = true,
                            RoomNumber = "202",
                            TypeID = 4
                        },
                        new
                        {
                            RoomID = 3,
                            HotelID = 3,
                            IsAvailable = true,
                            RoomNumber = "103",
                            TypeID = 2
                        },
                        new
                        {
                            RoomID = 4,
                            HotelID = 4,
                            IsAvailable = true,
                            RoomNumber = "204",
                            TypeID = 4
                        },
                        new
                        {
                            RoomID = 5,
                            HotelID = 5,
                            IsAvailable = true,
                            RoomNumber = "305",
                            TypeID = 5
                        },
                        new
                        {
                            RoomID = 6,
                            HotelID = 6,
                            IsAvailable = true,
                            RoomNumber = "106",
                            TypeID = 3
                        },
                        new
                        {
                            RoomID = 7,
                            HotelID = 7,
                            IsAvailable = true,
                            RoomNumber = "207",
                            TypeID = 2
                        },
                        new
                        {
                            RoomID = 8,
                            HotelID = 8,
                            IsAvailable = true,
                            RoomNumber = "108",
                            TypeID = 1
                        },
                        new
                        {
                            RoomID = 9,
                            HotelID = 9,
                            IsAvailable = true,
                            RoomNumber = "309",
                            TypeID = 4
                        },
                        new
                        {
                            RoomID = 10,
                            HotelID = 10,
                            IsAvailable = true,
                            RoomNumber = "110",
                            TypeID = 3
                        },
                        new
                        {
                            RoomID = 11,
                            HotelID = 11,
                            IsAvailable = true,
                            RoomNumber = "511",
                            TypeID = 5
                        },
                        new
                        {
                            RoomID = 12,
                            HotelID = 12,
                            IsAvailable = true,
                            RoomNumber = "212",
                            TypeID = 2
                        },
                        new
                        {
                            RoomID = 13,
                            HotelID = 13,
                            IsAvailable = true,
                            RoomNumber = "313",
                            TypeID = 4
                        },
                        new
                        {
                            RoomID = 14,
                            HotelID = 14,
                            IsAvailable = true,
                            RoomNumber = "414",
                            TypeID = 5
                        },
                        new
                        {
                            RoomID = 15,
                            HotelID = 15,
                            IsAvailable = true,
                            RoomNumber = "115",
                            TypeID = 3
                        },
                        new
                        {
                            RoomID = 16,
                            HotelID = 16,
                            IsAvailable = true,
                            RoomNumber = "216",
                            TypeID = 2
                        },
                        new
                        {
                            RoomID = 17,
                            HotelID = 17,
                            IsAvailable = true,
                            RoomNumber = "117",
                            TypeID = 1
                        },
                        new
                        {
                            RoomID = 18,
                            HotelID = 18,
                            IsAvailable = true,
                            RoomNumber = "318",
                            TypeID = 4
                        },
                        new
                        {
                            RoomID = 19,
                            HotelID = 19,
                            IsAvailable = true,
                            RoomNumber = "219",
                            TypeID = 2
                        },
                        new
                        {
                            RoomID = 20,
                            HotelID = 20,
                            IsAvailable = true,
                            RoomNumber = "220",
                            TypeID = 4
                        });
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.RoomImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.HasKey("ImageID");

                    b.HasIndex("RoomID");

                    b.ToTable("RoomImages");

                    b.HasData(
                        new
                        {
                            ImageID = 41,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-1?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 1
                        },
                        new
                        {
                            ImageID = 42,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-2?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 2
                        },
                        new
                        {
                            ImageID = 43,
                            ImageURL = "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 3
                        },
                        new
                        {
                            ImageID = 44,
                            ImageURL = "https://images.unsplash.com/photo-1501117716987-c8e6f8b7a6f8?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 4
                        },
                        new
                        {
                            ImageID = 45,
                            ImageURL = "https://images.unsplash.com/photo-1501117619481-8dde0d6d6aef?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 5
                        },
                        new
                        {
                            ImageID = 46,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-1?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 6
                        },
                        new
                        {
                            ImageID = 47,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-2?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 7
                        },
                        new
                        {
                            ImageID = 48,
                            ImageURL = "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 8
                        },
                        new
                        {
                            ImageID = 49,
                            ImageURL = "https://images.unsplash.com/photo-1501117716987-c8e6f8b7a6f8?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 9
                        },
                        new
                        {
                            ImageID = 50,
                            ImageURL = "https://images.unsplash.com/photo-1501117619481-8dde0d6d6aef?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 10
                        },
                        new
                        {
                            ImageID = 51,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-1?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 11
                        },
                        new
                        {
                            ImageID = 52,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-2?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 12
                        },
                        new
                        {
                            ImageID = 53,
                            ImageURL = "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 13
                        },
                        new
                        {
                            ImageID = 54,
                            ImageURL = "https://images.unsplash.com/photo-1501117716987-c8e6f8b7a6f8?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 14
                        },
                        new
                        {
                            ImageID = 55,
                            ImageURL = "https://images.unsplash.com/photo-1501117619481-8dde0d6d6aef?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 15
                        },
                        new
                        {
                            ImageID = 56,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-1?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 16
                        },
                        new
                        {
                            ImageID = 57,
                            ImageURL = "https://images.unsplash.com/photo-150Hotelsample-2?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 17
                        },
                        new
                        {
                            ImageID = 58,
                            ImageURL = "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 18
                        },
                        new
                        {
                            ImageID = 59,
                            ImageURL = "https://images.unsplash.com/photo-1501117716987-c8e6f8b7a6f8?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 19
                        },
                        new
                        {
                            ImageID = 60,
                            ImageURL = "https://images.unsplash.com/photo-1501117619481-8dde0d6d6aef?auto=format&fit=crop&w=1600&q=80",
                            RoomID = 20
                        });
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.RoomType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeID"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypeID");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            TypeID = 1,
                            BasePrice = 59.00m,
                            TypeName = "Single"
                        },
                        new
                        {
                            TypeID = 2,
                            BasePrice = 89.00m,
                            TypeName = "Double"
                        },
                        new
                        {
                            TypeID = 3,
                            BasePrice = 99.00m,
                            TypeName = "Twin"
                        },
                        new
                        {
                            TypeID = 4,
                            BasePrice = 189.00m,
                            TypeName = "Suite"
                        },
                        new
                        {
                            TypeID = 5,
                            BasePrice = 249.00m,
                            TypeName = "Deluxe"
                        });
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Address");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AvatarUrl");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Bio");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AmenityRoom", b =>
                {
                    b.HasOne("HotelBookingProject0.Models.Entities.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesAmenityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBookingProject0.Models.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsRoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.Amenity", b =>
                {
                    b.HasOne("HotelBookingProject0.Models.Entities.Hotel", null)
                        .WithMany("Amenities")
                        .HasForeignKey("HotelID");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.Booking", b =>
                {
                    b.HasOne("HotelBookingProject0.Models.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBookingProject0.Models.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.HotelImage", b =>
                {
                    b.HasOne("HotelBookingProject0.Models.Entities.Hotel", "Hotel")
                        .WithMany("Images")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("HotelBookingProject0.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.Review", b =>
                {
                    b.HasOne("HotelBookingProject0.Models.Entities.Hotel", "Hotel")
                        .WithMany("Reviews")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBookingProject0.Models.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.Room", b =>
                {
                    b.HasOne("HotelBookingProject0.Models.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBookingProject0.Models.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.RoomImage", b =>
                {
                    b.HasOne("HotelBookingProject0.Models.Entities.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.UserProfile", b =>
                {
                    b.HasOne("HotelBookingProject0.Models.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("HotelBookingProject0.Models.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HotelBookingProject0.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HotelBookingProject0.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBookingProject0.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HotelBookingProject0.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.Hotel", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelBookingProject0.Models.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Profile");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
